trigger:
  branches:
    include:
    - main
  paths:
    include:
    - '**'

pr: none

pool: 
  vmImage: 'windows-latest'

variables:
- name: PYTHONUTF8
  value: 1
- group: fabric-cicd
  
jobs:
- job: 'deploy'
  displayName: 'PROD deployment'

  steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python 3.11'
      inputs:
        versionSpec: 3.11

    - task: PowerShell@2
      displayName: 'Install necessary libraries'
      inputs:
        targetType: 'inline'
        script: |
          python -m pip install --upgrade pip
          pip install -r "$(Build.SourcesDirectory)\cicd\requirements.txt"
        pwsh: true

    - task: PythonScript@0
      displayName: 'Run script to deploy with fabric-cicd to PRO'
      inputs:
        scriptPath: '$(Build.SourcesDirectory)\cicd\scripts\orchestrator.py'
        arguments: '--ParentDirectory "$(Build.SourcesDirectory)" --Environment "PROD"'